ads = [
	"Christmas Sale. Handmade gifts for the hard-to- find person.",
	"Fully cooked boneless smoked man $2.09 lb.",
	"Lost – Donkey, wearing a pink halter, Monterey Center – 269-793-….",
	"EXERCISE EQUIPMENT: queen size mattress & box spring – $175.",
	"WANTED: Someone to grind or chew hay for horse with bad teeth. Contact James “Bud” Williams, 942-…. Carterville",
	"For Sale: exercise bike good as new. Please call Mrs. Stout.",
	"Mediterranean Villa – rooms located just steps to the ocean/park/and golf course. Sunsets every day. $209,950",
	"Manure Digester Summit, 9:30am–3pm, $20 includes lunch…",
	"Fort Hays State University – Honro roll…",
	"Free Golf! – Free Sleeve of Golf Balls! – With the purchase of a $39 hotdog plus tax (includes chips and drink)…",
	"Thurs. – Skateboard Expo will be from 4 pm to 5:30 pm E. Center Street. Free. Sponsored by the Rochester Area Brain Injury Community Committee.",
	"EVANGELIST: ROGER HILLIS • Morning Service 10:30 a.m. – “Preparing For Marriage” • Evening service 6:00 p.m. – “A Look At Hell”",
	"Now you can own the number one car in America for two consecutive years.",
	"Ambulance Service – Non-Emergency – Sims Funeral Home",
	"Novara Arosa Bike Jersey, retailing for $55 at REI is made of insulting fabric for cool-weather riding…",
	"You're a brunette, 6', long legs, 25-30, intelligent, articulate and drop dead gorgeous. I, on the other hand, have the looks of Herve Villechaize and an odour of wheat. No returns and no refunds at box no. 3321.",
	"Ashes to Portraits – is a unique, ONE-OF-A-KIND concept. We create beautiful painted portraits using your loved one’s ashes and our secret mixture of oil paint!…",
	"DOWNERS GRTOVE – Stonewall Ave. Sat 10/18 & Sun 10/19 9am – 5pm – Dead Peoples Old Stuff. Oak stenciled table, tools, medical aids, Whirlpool, wheelchair, casino items, beer signs, many collectibles.",
	"Cat for Sale: This cat will eat anything and go to the bathroom anywhere too.",
	"Cure Sleepiness Right Away – Time for Use: Long-Distance Driving, Drunk Driving, Night Driving…",
	"’06 Frod Focus $9,999",
	"Smile of the Week • I’m smiling because “I am going to buy some sheep.” Sonny Clements, Manzanola",
	"For Sale: Basketball Hoop and backboard. Only used for dunking kid brother.",
	"Sean – You are such a disappointment to the entire family – don’t bother coming home. Love, Dad",
	"Wanted: Preparer of food. Must like the food business, be dependable, and be willing to get hands dirty.",
	"SECRETARY – needed for quick lube. 6 Days. Call… Stuyvesant Ave, Union, NJ.",
	"COME TO WORK for Subway and have your dreams crushed like the rest of us. Weekends required. 941-…. after 2 pm.",
	"QUESTION OF THE DAY – Question: What constitutes a millionaire?  •  Answer: A millionaire is someone who has $1 million, according to Jerry Beto, branch manager and senior vice president of investments at AG Edwards and Sons.",
	"Buy a 3-Piece Livingroom Set – Get a 3-Piece Glass and Brass End Table…",
	"2008 Cherokee Lardo “Diesel” …",
	"Soccer ball signed by either Pele, the former Brazilian soccer player widely renowned by most experts and fans to be the finest player that has ever existed, or by some guy named “Peter.”  $75.",
	"Come to Our Open House  From 1pm – 4 pm – EASY TO FIND – South I-25 Exit #173 Larkspur to Perry Park Ave., Right on Perry Park Ave., Right on Silverheels Rd., Right on Eagle Rd., Right on Tenderfoot, Left on Shrine Rd., Left on Independence, Right on Cameron",
	"CORRECTION – Due to incorrect information received from the Clerk of Courts Office, Diane K. Merchant, 38, [address] was incorrectly listed as being fined for prositution in Wednesday’s paper. The charge should have been failure to stop at a railroad crossing. The Public Opinion apologizes for the error.",
	"WANTED: Man to wash dishes and two waitresses.",
	"Sewer / Manhole Repair Worker – experienced only. Immediate opening.",
	"COUPON – Mighty Dog dog Coffee– 2 cans $1…",
	"LOST • MISSING DOG: Small Golden Brown Palm Iranian lost in Gramercy. If you have any information, please call 869-….",
	"’83 Toyota hunchback – $2000",
	"Wanted, man to take care of cows that does not smoke or drink.",
	"Free 1 can of pork & beans with purchase of 3 br 2 bth home.",
	"FREE DUCKS. You catch.",
	"Our bikinis are exciting.  They are simply the tops.",
	"Garage sale: Come and partake of the drapes of wrath, sofas choice, star dreck, broken china syndrome, laricats of wire and rubble without cause.",
	"Slut in the kitchen, chef in the bedroom. Woman with mixed priorities (37) seeks man who can toss a good salad.",
	"Correction – A headline on an item in the Feb. 5 edition of the Enquirer-Bulletin incorrectly state “ Stolen groceries.” It should have read “Homicide.”",
	"Sterling Optical – FREE eye with Purchase of a Prescription Pair of Eyeglasses",
	"Turkey Shoot Slated – The Malheur Gun Club will hold a turkey shoot Sunday at the Vale Airport… Winners will receive hams.",
	"Beat the Christmas Holiday Rush – Order Now – Choosing your Monument now, means your loved ones won’t be faced with the hardship during their time of grief.  STEEDLEY MONUMENT WORKS",
	"TO LET: 4 bedroom house close to town. No poets.",
	"’83 Toyota hunchback – $2000",
	"’06 Frod Focus $9,999",
	"Incurable romantic, seeks filthy whore. Phone…",
	"Are all on-line realtors created equal? No, there's only one!",
	"To all you hunters who kill animals for food, shame on you; you ought to go to the store and buy the meat that was made there, where no animals were harmed.",
	"WANTED: Part-Time secretary with wisdom of Deborah, dedication of Dorcas, stay cool under fire like Shadrach, imagination of the prophets, capabilities of all scribes.",
	"ATTENTION! Federal Employees With Work-Related Hearing Loss – LISTEN TO THIS! – If Your Claim For Hearing Loss Was Accepted By The U.S. Department Of Labor – OWCP, You May Be Eligible For Continuing Benefits",
	"Mrs. Jody Defries is pleased to announce the arrival of Elijah Joel – 8 pounds 10 ounces… and the loss of twenty pounds.",
	"Now you can borrow enough money to get out of debt.",
	"ARTIFICIAL CHRISTMAS TREE – For Sale. Like new. Needs stand, ornaments, lights, and branches. $99.00 firm. Call…",
	"Wanted: Lifeguard. Must be able to swim.",
	"WANTED: Man to wash dishes and two waitresses.",
	"Time management seminar. Washington County Library, St. George Branch… About six or sevenish.",
	"Super Bowel Party – Sunday January 30th – Complimentary Buffet…",
	"FREE PUPPIES…  part German shepherd, part dog",
	"Dear recently-expired subscriber…",
	"Car Sitting Services: Are you going away for a long trip? Are you afraid your car will be lonely, or worse yet, stolen!? I can protect your car and take it for long drives to keep it company. I can even drop you off and pick you up at the airport using your car (at my convenience)! Cheap rates! Call [telephone] and ask for One-tooth Tony.",
	"YOUTH PROGRAMS • GENERAL/SOCIAL – Skydiving for Tots – (ages 10 mos.–2 years) Introduce your toddler to the fun and thrill of skydiving before he or she develops unwarranted fears of freefalling. Certified jump instructor…",
	"FOR SALE – Easy chair, Kitchen table, Chester Drawers. 982-….",
	"WANTED. Hunting rifle, suitable for teenagers.",
	"FREE YOUNG GOAT for butchering or companion animal, call…",
	"Amana washer $100. Owned by clean bachelor who seldom washed.",
	"FREE TO A GOOD HOME: Shemale Jack Russell Terrier, 14 mos., has shots, needs fenced yard. 619-445-….",
	"Wanted: Hard working, experienced farm woman. Household and field work; know how to cook; must own tracter –- send photo of tractor.",
	"HELP WANTED – DoodyCalls Technician",
	"ATTORNEY WANTED that is not a liar or a thief. Phone…",
	"German shepherd. 85 lbs. neutered. speaks German. free.",
	"Over 300 people in Napa Valley are assaulted each year. Volunteer to help.",
	"Easygoing athletic SJM, 41, seeking SF, looks not important, must be tall, slim and attractive.",
	"hairorobert – IF WE CAN’T MAKE YOU LOOK GOOD…  YOU UGLY! – 757-….",
	"This house has been fully insulted.",
	"WANTED: 30 Chinamen and a zeppelin for elaborate practical joke. Can you help? Please call…",
	"Sheer stockings.  Designed for fancy dress, but so serviceable that lots of women wear nothing else.",
	"Cat for Sale: This cat will eat anything and go to the bathroom anywhere too.",
	"AMANDA – I’m running a bit late. Will be there in about an hour. How far apart are the contractions?",
	"Wanted: Preparer of food. Must like the food business, be dependable, and be willing to get hands dirty.",
	"SUBURBAN – SEE WAL-MART! From your private deck, high in the hills of Wyomissing! 5 BRs, 2 fpls. Spacious floor plan! $269,900.",
	"We build bodies that last a lifetime.",
	"DOWNERS GRTOVE – Stonewall Ave. Sat 10/18 & Sun 10/19 9am – 5pm – Dead Peoples Old Stuff. Oak stenciled table, tools, medical aids, Whirlpool, wheelchair, casino items, beer signs, many collectibles.",
	"My name was printed incorrectly below my letter in the December 30 issue of the Sevenoaks Chronicle. It should read L P Pook, not L P Hook. (signed) L P Hook   –  Sevenoaks Chronicle",
	"WANTED. Hunting rifle, suitable for teenagers.",
	"CHRISTIAN woman looking for Christian man partner who is sympathetic with woman who has mental illness and hears voices but is self controlled. Phone…",
	"2 wire mesh butchering gloves, 1 5-finger, 1 3-finger, pair: $15",
	"Bring a smile to a child's face with a life-threatening illness.",
	"MLS#2110… Nobody has died yet on these 11.90 acres. Small home, wood, pasture, stream. $144,900 740-965-….",
	"Amana washer $100. Owned by clean bachelor who seldom washed.",
	"FREE Rent in exchange for elderly woman. 319-233-….",
	"10 FREE French Fry Certificates for only $1.00",
	"COLD-A-SACK SALE on Lorine Ln. 5 family yard sales. Sat. 8-? Follow signs off 467 & Good Luck Rd. – Baby up to plus size clothing, furn., tools, & X-mas.",
	"PIG – I saw you at Tiki Bobs. You grabbed my butt and I told you if you did that again I’d kill you. You did. I need your address now. Phone…",
	"Love is strange – wait 'til you see my feet. F, 34, wide-fitting Scholl's.",
	"If you sign up today for a full year's service by February 10th…",
	"Advanced Products, Inc. • 605 East Robins, Conway, Arkansas 72032 • 10% Satisfaction Guaranteed • DIRECTIONS – Take 1 to 3 tablets daily after breakfast as a dietary supplement.",
	"ARTIFICIAL CHRISTMAS TREE – For Sale. Like new. Needs stand, ornaments, lights, and branches. $99.00 firm. Call…",
	"Chronically Overweight? 6 p.m. 522 N. Eighth St., Sheboygan… Bring your own chair. Free.",
	"Wanted: Lifeguard. Must be able to swim.",
	"ATTORNEY WANTED that is not a liar or a thief. Phone…",
	"Home Made Portable Toilet. Great for parades $90/ 764-….",
	"Full sized mattress. 20 year warranty.  Like New.  Slight urine smell.",
	"You're a brunette, 6', long legs, 25-30, intelligent, articulate and drop-dead gorgeous. I, on the other hand, am 4'10\", have the looks of Herve Villechaize and carry an odor of wheat. No returns and no refunds at box…",
	"BOX OF Twinkies, 10 years old, two missing, rest have cream filling sucked out, $5.  Call 217-….",
	"Nordic track $300 – hardly used – call Chubby.",
	"MARCH MADNESS MOVE-IN DEAL! Move in by March 31st, pay no rent until April 1st!…",
	"Wanted: Part-time married girls for soda fountain in sandwich shop.",
	"Meet the new face of indoor bowling! More or less the same as the old face, but less facial hair and better teeth. M, 28. Box no. 3377.",
	"CORRECTION – In a recipe for salsa published recently, on of the ingredients was misstated…  The correct ingredient is “2 tsp. of cilantro” instead of “2 tsp. of cement.”",
	"Holcross pullets. Starting to lay Betty Clayton, Call…",
	"CUSTOMER SERVICE REP – FT/PT Strong phone skills and able to handle high call volume. Light collection. Fast paste work enviorment. Fax resume…",
	"FREE: farm kittens. Ready to eat.",
	"Get 50% off or half price, whichever is less.",
	"COLD-A-SACK SALE on Lorine Ln. 5 family yard sales. Sat. 8-? Follow signs off 467 & Good Luck Rd. – Baby up to plus size clothing, furn., tools, & X-mas.",
	"Your buying me dinner doesn't mean I'll have sex with you. I probably will have sex with you, though. Honesty not an issue with opportunistic male, 38.",
	"Semi-Annual after-Christmas Sale.",
	"Save regularly in our bank.  You'll never reget it.",
	"Theft: A woman in the 1900 block of 129th Lane Northeast reported Oct. 15 that someone must have stolen her mail, because she did not receive birthday cards from some of her friends.",
	"Wanted to Rent – Wanted: Room to rent. Saudi Arabia students are looking for American families to live with. Call Osamah at 419-….",
	"Wanted: Lifeguard. Must be able to swim.",
	"All day starting at 1 PM. – Shuck N' Jive's Annual Crawfish Boil",
	"Singer/lyricist looking for untalented musicians to form punk band. Call… & ask for Adam.",
	"BABY SITTER NEEDED. Imaginative, neutering, playful & dependable? Weekdays 12–5PM. Must have own car. Ref. required. Call 882-….",
	"Come to Our Open House  From 1pm – 4 pm – EASY TO FIND – South I-25 Exit #173 Larkspur to Perry Park Ave., Right on Perry Park Ave., Right on Silverheels Rd., Right on Eagle Rd., Right on Tenderfoot, Left on Shrine Rd., Left on Independence, Right on Cameron",
	"CORRECTION – In a recipe for salsa published recently, on of the ingredients was misstated…  The correct ingredient is “2 tsp. of cilantro” instead of “2 tsp. of cement.”",
	"Lustful? Sinful? Sexual? These are all words not used in conjunction with my feeble, limp form for at least 32 years. You are a woman to 40 with high class looks and low class mind. I am an ever growing vessel of limp wristed sexual energy just waiting to be shook. You may call me sir. box no. 32/02",
	"Mt. Kilimanjaro, the breathtaking backdrop for the Serena Lodge. Swim in the lovely pool while you drink it all in.",
	"POMERANIAN POPPIES per bread, 7 wk. on 4-16-08 decals removed, teddy bear faces, very cute, $300 884-….",
	"Get 500 free minutes of airtime for only $50.",
	"A-Whole Chiropractic • Body Injury Experts • Auto/Work Accidents…",
	"WANTED: Medium sized dog house for low income family. Call 269-….",
	"Now you can borrow enough money to get out of debt.",
	"The One Gallon Hip Flask…",
	"Turkey Shoot Slated – The Malheur Gun Club will hold a turkey shoot Sunday at the Vale Airport… Winners will receive hams.",
	"ETERNAL ASCENT – sends cremated remains to the heavens in a special balloon. Let us help make your loved one’s final journey a memorable one. We also release pets. Call 800-808-….",
	"Views plus spacious 1554 sq. ft. home with large lot, family room with fireplace, huge dick for entertaining? …",
	"Artie's Restaurant and Yogurt Parlor – An Alternative to Good Eating.",
	"HELP WANTED – PlayStation Brand Ambassador",
	"WE FILL ALL PRESCRIPTIONS We Fill All Compounded (Mixed) Prescriptions According To Your Doctor’s Instructions. If Your Doctor Writes You A Prescription For A Specially Prepared Suppository, We Can And Will Fit It….",
	"In reply to your valued enquiry, we enclose illustrations of Dining Tables of Oak, seating fourteen people with round legs and twelve people with square legs, with prices attached.",
	"This going-out-of-business sale is for a limited time only.",
	"2008 Cherokee Lardo “Diesel” …",
	"… featuring Kohler Lite Flush Toilets – Live Demonstration – See How They Perform…",
	"Free internet access … $99.",
	"HELP WANTED – PlayStation Brand Ambassador",
	"Rubber woman almost new used only 3Xs $10 OBO. 879-….",
	"FOR SALE – musky dimes. Call…",
	"FOR SALE: Doctor’s sailing dinghy and accessories. Doctor no further use.",
	"Free Golf! – Free Sleeve of Golf Balls! – With the purchase of a $39 hotdog plus tax (includes chips and drink)…",
	"No matter what your top coat is made of, this miracle spray will make it really repellent.",
	"Save regularly in our bank.  You'll never reget it.",
	"Mother’s helper – peasant working conditions.",
	"Cute kitten for sale. Two cents or best offer.",
	"SALVADORE DOLLY PRINT, frame, dated, signed cert. $600/obo Must sell 941-723-….",
	"JACK RUSSELL terrorist puppies. 2 boys, 2 girls, 5 weeks old. $400 each. 725-….",
	"Shakespeare's Pizza – Free Chopsticks",
	"Fulham Football Club seeks a Manager / Genius",
	"Going back to school was the best thing I ever done.",
	"TURKEY – FOR SALE. Partially eaten. Only eight days old.  Both drumsticks still intact. $23.00 OBO",
	"WANTED: 30 Chinamen and a zeppelin for elaborate practical joke. Can you help? Please call…",
	"Lost Cocktail.",
	"1 man, 7 woman hot tub – $850/offer",
	"Unashamed triumphalist male for the past 46 years. Will I bore you? Probably. Do I care? Probably not.",
	"German shepherd. 85 lbs. neutered. speaks German. free.",
	"OPEN HOUSE body shapers toning salon free coffee & donuts",
	"Display PostScript running under the Windows windowing system demonstrates the ability to display OpenStep applications inside Windows windows, alongside native Windows applications. This seamless window system integration is a milestone in porting to Windows and demonstrates that OpenStep for Windows will be a good Windows citizen.",
	"Ashes to Portraits – is a unique, ONE-OF-A-KIND concept. We create beautiful painted portraits using your loved one’s ashes and our secret mixture of oil paint!…",
	"2008 Cherokee Lardo “Diesel” …",
	"HELP WANTED – PlayStation Brand Ambassador",
	"EXPERIENCED NANNY – To care for 3 young kids in out house 30 hours a week. Must drive and have references. Call Christine at 305-294-….",
	"Lost Cocktail.",
	"LAWN MOWER – Tends to catch on fire but put out easily with garden hose $30. Please call 258-….",
	"Pollard Used Cars – Limited Time Offer! – $299 per month – For the Rest of Your Life",
	"The Brandywine Gourmet – Stop in to enter drawing to guess height & weight of our GIANT 3 ft., 20 lb. Chocolate Bunny!…",
	"Novara Arosa Bike Jersey, retailing for $55 at REI is made of insulting fabric for cool-weather riding…",
	"Pennzoil/Quaker State OIL CHANGE – $12 plus oil & filter",
	"RABIES CLINIC & BAKE SALE 1–3 PM – $8.00/Animal – Keezletown Ruritan Hall…",
	"Beautiful uncommon African follis dish, 550,00,000 yrs. old, $45.",
	"SNOW BLOWER for sale… only used on snowy days.",
	"SECRETARY – needed for quick lube. 6 Days. Call… Stuyvesant Ave, Union, NJ.",
	"Used Tombstone, perfect for someone named Homer HendelBergenHeinzel. One only.",
	"Enthusiastic and alive with a desire to lead others",
	"20 dozen bottles of excellent Old Tawny Port, sold to pay for charges, the owner having lost sight of, and bottled by us last year.",
	"1995 NISSAN Maxima, green, leather, loaded, CD, auto start, sunroof, 4-door, good condition, $4500. Not for sale.",
	"If you have over forty eyes and have noticed how your vision has changed…",
	"SITUATIONS WANTED – WILL CLEAN your home, will take in washing & ironing in my home. Will also tattoo pet dog at your home. 297-….",
	"CONDOS & TOWNHOUSES – Designer condo – Spacious 3 bed/2.5 ba. Tastefully redone in ’04. dine area. Kit w/subzero, stainless apps, granite ctrs, custom cabinetry. New Baths. Hrdwd flrs, crown molding. City views. Much more. 23 Hour security bldg…",
	"At the Frederick Fairgrounds – German Bands – Petting Zoo – Mini Race Cars – Have a Horse sit on your lap! …",
	"Wanted: Limo driver needed for overnight transport of drunk and drugged up clients.",
	"Smith & Wesson – For the Bride To Be! – Model 642 .38 Special $419.97, Save $50…",
	"Bring a smile to a child's face with a life-threatening illness.",
	"No matter what your topcoat is made of, this miracle spray will make it really repellent.",
	"To all you hunters who kill animals for food, shame on you; you ought to go to the store and buy the meat that was made there, where no animals were harmed.",
	"Free puppies: ½ cocker spaniel, ½ sneaky neighbor’s dog.",
	"Amana washer $100. Owned by clean bachelor who seldom washed.",
	"Genuine Imitation Jungle Boots",
	"YOUTH PROGRAMS • GENERAL/SOCIAL – Skydiving for Tots – (ages 10 mos.–2 years) Introduce your toddler to the fun and thrill of skydiving before he or she develops unwarranted fears of freefalling. Certified jump instructor…",
	"We have a large selection of shirts for both mens and ladies.",
	"FREE PUPPIES…  part German shepherd, part dog",
	"FREE – GENUINE faux 9 CARAT SAPPHIRE PENDANT…",
	"Potty Chair, solid oak, light brown stain. $20",
	"Wanted: Hard working, experienced farm woman. Household and field work; know how to cook; must own tracter –- send photo of tractor.",
	"Buy a 3-Piece Livingroom Set – Get a 3-Piece Glass and Brass End Table…",
	"Landscaping Labor – the new Green Party…",
	"FOR SALE: Cemetery needs. Monuments, Sales, Dating, Letterings. Call Dennis Leibfried before you go. Ph.507…",
	"TOYOTA SCION • Coffin with 52 inch sunroof – $21,800",
	"We'll move you worldwide throughout the country.",
	"AMERICAN FLAG – 60 stars. Pole included $100. Call…",
	"92’ BLK VOLKSWAGON CABRIOLET Answers to the name April. Last seen in Towson near the YMCA. Yes, Owner is Blonde. If found please call Button…",
	"CLASSIFIED: An unexpected vacancy for a knife-thrower's assistant. Rehearsals start immediately.",
	"Braille dictionary for sale.  Must see to appreciate.",
	"Is your memory letting you down?  And what about your memory?  Is it letting you down?  Call for information pack right now.  Before you forget. 079…",
	"FOR SALE: greens, turnips, collards, mustard, and rudebeggers. One mile west of Westiville, First clay road on left. Call…",
	"Allan’s Aquarium & Pet Center  – After-Easter Tarantulas – The Gift for the Person Who Has Everything…",
	"Sterling Optical – FREE eye with Purchase of a Prescription Pair of Eyeglasses",
	"You're a brunette, 6', long legs, 25-30, intelligent, articulate and drop dead gorgeous. I, on the other hand, have the looks of Herve Villechaize and an odour of wheat. No returns and no refunds at box no. 3321.",
	"Great Dames for sale.",
	"USED BOOB SALE – Where: Jefferson Pointe Mall  When: Fri & Sat, Sept 9 & 10 10am–9pm, Sunday 12–5 pm  What: 20 plus categories. Many in fine shape.",
	"’06 Frod Focus $9,999",
	"WANTED: Somebody to go back in time with me. This is not a joke. P.O. Box ###, Oakview, CA 93022. You'll get paid after we get back. Must bring own weapons. Safety not guaranteed. I have only done this once before.",
	"Nice Parachute – Never opened.  Used once.",
	"HEY KIDS…  Santa will be at Viking Liquor Sunday Nov. 26, 11 am–3 pm FREE PICTURES • VIKING LIQUOR • KIDS! Bring your pet!",
	"WANTED – COMMERCIAL SPACE HUNTER",
	"*1990 SUBARU Justy. 5-speed, fuel injection, new brake and drum. New exhaust system, 4 new street tires and 2 studded. Body in great shape. Engine gone, but still runs. $500. 247-….",
	"Wanted. Man to take care of cow that does not smoke or drink.",
	"FREE PUPPIES. – Mother, a Kennel Club registered German Shepherd. Father, Super Dog… able to leap tall fences in a single bound.",
	"FREE TO A GOOD HOME: Shemale Jack Russell Terrier, 14 mos., has shots, needs fenced yard. 619-445-….",
	"HAVE YOU SEEN OUR COW? Female, Black with white face. Red tag in her ear. She was last seen on County Rd. 45. Please call Ann Smith at…",
	"Wanted. Man to take care of cow that does not smoke or drink.",
	"Friday, March 27 – Lenten Fish Dinner – St. Ann Parrish – Tickets can be purchased at the door or by calling Christ at 522 -….",
	"06’ Suzuki GSXR 1000 • Fourways, Johannesburg – This bike is perfect! Only done 7000 kms and has had its 1500 km. dealer service. No falls/scratches. I use it as a cruiser/commuter. I’m selling it because it was purchased without proper consent of a loving wife. Apparently “do whatever the f**k you want” doesn’t mean what I thought. Call me, Steve. (011) 867-….",
	"Garage sale: Come and partake of the drapes of wrath, sofas choice, star dreck, broken china syndrome, laricats of wire and rubble without cause.",
	"Free inside mini golf. Call ahead, because play is canceled if there is any funeral work. “We want folks to know we’re not so scary” we’re people. A funeral parlor is not a dark place, but a safe and secure one…",
	"Sinister-looking man with a face that only a mother would love: think of an ageing Portillo with a beard and you have my better-looking twin. Sweetie at heart, though. Nice conversation, great for dimly-lit romantic meals. Better in those Welsh villages where the electricity supply can't be guaranteed. Charitable women to 50 appreciated. Box…",
	"WANTED: 12 volt electric wench, must be reasonable… 24 Hour Service – Animal Control – Joe Sweeney – Removal Of Nuisance Wild Animals • Chimney Caps • Rats & Bats (203) 421-….",
	"Advanced Products, Inc. • 605 East Robins, Conway, Arkansas 72032 • 10% Satisfaction Guaranteed • DIRECTIONS – Take 1 to 3 tablets daily after breakfast as a dietary supplement.",
	"Star Wars Job of the Hut – $15",
	"Terra Andina Sauvignon Blanc, 2007 $9.99 – Intense, vibrant cat pee aroma underscored by tangerine and grass; crisp, clean and tart with…",
	"Ground beast, 99 cents/lb.",
	"Are all on-line realtors created equal? No, there's only one!",
	"Braille dictionary for sale.  Must see to appreciate.",
	"FREE TO GOOD COUNTRY HOME – ¾ Rottweiler, ¼ Shepherd, 3 years old, female, spayed, very intelligent, loves to eat live rabbits and kittens, loves to play ball with kids. Call after 5:00 pm.. (614)…",
	"How to Speak and Write Like A Colleg [sic] Graduate",
	"Professional Texas Hold’em Polka Table, new, still in box. $250/best 508-916-….",
	"FOR SALE: 1993 Chevy Lumina. Black exterior with beige interior. Runs and drives great. Sorry, no tires included.",
	"ATTORNEY WANTED that is not a liar or a thief. Phone…",
	"Singer/lyricist looking for untalented musicians to form punk band. Call… & ask for Adam.",
	"A Race to Savings! – with Thank You Card – $119 – without card $2.39",
	"Amana washer $100. Owned by clean bachelor who seldom washed.",
	"Harrisburg Postal Employees Gun Club",
	"TOYOTA SCION • Coffin with 52 inch sunroof – $21,800",
	"Wanted F-T Physical Therapy Director – Licensed in Texas with supervisory experience – We Drug Test – EOE – Tabasco Free Facility –Competitive Compensation and Benefits Program. Contact…",
	"FOR SALE: Lee Majors (6 Million Dollar Man) – $50",
	"SURGEON WANTED for a new health clinic opening in the area. No experience needed. Must have own tools.",
	"Joining nudist colony, must sell washer & dryer $300.",
	"HANDSOME RAKE – Out of work leaf raker/bagger seeks whimsical beauty with unkempt auburn orc hestnut hair, cool with coarse hands and a penchant for whistling. mellow… mo, 28, …",
	"Selection As Big As The North Pole.",
	"RICH INDIVIDUAL – wishes to help the needy poor. Send $2 for more information to: R.S., Santa Monica Bl. #280 Beverly Hill, CA 90210",
	"WE FILL ALL PRESCRIPTIONS We Fill All Compounded (Mixed) Prescriptions According To Your Doctor’s Instructions. If Your Doctor Writes You A Prescription For A Specially Prepared Suppository, We Can And Will Fit It….",
	"Hummels – largest selection ever – if it’s in stock, we have it!",
	"3 bedroom house for sale: new gas furnace, new wiring and new water heater won't last long!",
	"Over 300 people in Napa Valley are assaulted each year. Volunteer to help.",
	"Turkey Shoot Slated – The Malheur Gun Club will hold a turkey shoot Sunday at the Vale Airport… Winners will receive hams.",
	"Information – MENTALLY ILL NEEDED – To interview for Novel. Must be successful & interesting. Email: …@trsemail… (614) 537-….",
	"BELZ Factory Outlet Mall – Redeem this coupon at the Mall Office for a coupon",
	"Channel 16 temporarily off the air due to technical improvements",
	"WANTED. Hunting rifle, suitable for teenagers.",
	"SUPERINTENDED NEEDED",
	"Bet us your letter of business translation do. Every people in our staffing know English like the hand of their back. Up to the minuet wise-street phrases, don't you know, old boy.",
	"Ensure your next erection is in safe hands.",
	"Tattoos done while you wait.",
	"Food Stamps Excepted [sic]",
	"ADVERTISING COMPANY NEED one male talent, shooting the back only with our product kitchen stuff, please send your picture. If you are interested…",
	"If you sign up today for a full year's service by February 10th…",
	"FOR SALE • OLDER CLOTHES DRYER. Works well but needs new home. Will trade for 2 large packages Oreo double stuffed cookies (unopened). Phone…",
	"Dog for sale: eats anything and is fond of children.",
	"GE Mammogram dish washer for sale, white $20. Good condition. (805) 523-….",
	"QUESTION OF THE DAY – Question: What constitutes a millionaire?  •  Answer: A millionaire is someone who has $1 million, according to Jerry Beto, branch manager and senior vice president of investments at AG Edwards and Sons.",
	"If you have one of these symptoms, please call this 800 number – Death, Heartburn, …",
	"$17,962 – ’98 Lincolon Town Car",
	"Gifts for Men – Silk Boxers – Silk Robes – Silk Pajamas – Silk G-Strings – Silk Boxer Briefs – and be sure to see our Nutcracker Shorts",
	"SAFEWAY – NOW ACCEPTING APPLICATIONS – FOR TEMPORARY EMPLOYEES IN PREPARATION FOR A POSSIBLE LABOR DISPUTE – Cashiers, Clerks, Customer Service – $12.00/hour – PLease contact…",
	"Hummels – largest selection ever – if it’s in stock, we have it!",
	"LOST – WEDDING RING, men’s, Hooters’s parking lot, 6/27, Reward! Call…",
	"They call me Naughty Lola. Run of the mill beardy physicist – male, 46.",
	"FOR SALE:  One pair hardly used dentures, only 2 teeth missing.  $100 OBO.  Call Ira…",
	"In reply to your valued enquiry, we enclose illustrations of Dining Tables of Oak, seating fourteen people with round legs and twelve people with square legs, with prices attached.",
	"FOR SALE – Diamonds $20; microscopes $15.",
	"Super Bowel Party – Sunday January 30th – Complimentary Buffet…",
	"COUPON – Mighty Dog dog Coffee– 2 cans $1…",
	"856-981-….  $1.00 OFF Any Job Over $800",
	"SUPERINTENDED NEEDED",
	"Not everyone appearing in this column is a deranged cross-dressing sociopath. Let me know if you find one and I'll strangle him with my bra. Man, 56.",
	"BOX OF Twinkies, 10 years old, two missing, rest have cream filling sucked out, $5.  Call 217-….",
	"Terra Andina Sauvignon Blanc, 2007 $9.99 – Intense, vibrant cat pee aroma underscored by tangerine and grass; crisp, clean and tart with…",
	"FOR SALE: Instant coffee table",
	"Manure Digester Summit, 9:30am–3pm, $20 includes lunch…",
	"IMPORTANT! IMPORTANT!  Anyone who has had a bone scan within the last 5 years where your knees have been strapped to your crotch with a 6” belt, please call (815) 522-….",
	"OUR SOFA seats the whole mob and it's made of 100% Italian leather.",
	"SURGEON WANTED for a new health clinic opening in the area. No experience needed. Must have own tools.",
	"Snake for sale. Five-foot boa constrictor – only $5 per foot.  Must buy entire length.",
	"FOR SALE: Lee Majors (6 Million Dollar Man) – $50",
	"Orange, missing since 21st in Lakewood, $25 reward",
	"Wanted, man to take care of cows that does not smoke or drink.",
	"WANTED: Used Paint",
	"WANTED: chambermaid in rectory. Love in, $200 a month. References required.",
	"2 female Boston Terrier puppies, 7 wks old, perfect markings, 555-1234.  Leave mess.",
	"Our bikinis are exciting.  They are simply the tops.",
	"SPANISH TOOTER NEEDED FOR A 7 year old student, learn to speak and write fluently. Call after 6 pm. 467-….",
	"Wanted: Preparer of food. Must like the food business, be dependable, and be willing to get hands dirty.",
	"Free puppies: ½ cocker spaniel, ½ sneaky neighbor’s dog.",
	"Pollard Used Cars – Limited Time Offer! – $299 per month – For the Rest of Your Life",
	"Foot tasting, [sic] arranged through the courtesy of Marks & Spencers and Safeway, gives customers a rare chance to try some of those more exotic flavors.",
	"WANTED: chambermaid in rectory. Love in, $200 a month. References required.",
	"Soft & genital bath tissues or facial tissue 89 cents",
	"ONE METAL Office desk. Timeshare, sleeps six, at Alpine Bay, Alabama. 859-….",
	"Bastard. Complete and utter. Whatever you do, don't reply – you'll only regret it.",
	"If You Had No Idea What To Get Her For Valentine’s Day… Imagine How Overwhelming Arranging Her Funeral Would Be.  Give her the perfect gift, make pre-arrangements as a couple with the affordable funeral home. Choose from affordable funeral services or affordable cremations. Compassion is our passion…",
	"Spakling Wines – with Iron Horse Vineyards – a blend of 30% Chardonnay…",
	"MANAGEMENT POSITIONS AVAILABLE – Contact Tony – Vacation, uniforms, meals and possible salary – McDonald’s",
	"$17,962 – ’98 Lincolon Town Car",
	"COLD-A-SACK SALE on Lorine Ln. 5 family yard sales. Sat. 8-? Follow signs off 467 & Good Luck Rd. – Baby up to plus size clothing, furn., tools, & X-mas.",
	"FOR SALE. Three canaries of undermined sex.",
	"Give Dad What He Always Wanted! A Weekend For Both of You in The Nude. • We Set The Mood. You Provide The romance. • They are back… Paradise Valley Resort – Georgia’s Premier Clothing Optional Resort – 3 pools • 2 hot tubs • NO CLOTHING! – Day Visitors Welcome …",
	"Amana washer $100. Owned by clean bachelor who seldom washed.",
	"You're a brunette, 6', long legs, 25-30, intelligent, articulate and drop-dead gorgeous. I, on the other hand, am 4'10\", have the looks of Herve Villechaize and carry an odor of wheat. No returns and no refunds at box…",
	"Fresh-Cut CHRISTMAS TREES Arriving December 28th – We Carry the Fullest Freshest Trees Available…",
	"See ladies blouses. 50% off!",
	"To all you hunters who kill animals for food, shame on you; you ought to go to the store and buy the meat that was made there, where no animals were harmed.",
	"Allan’s Aquarium & Pet Center  – After-Easter Tarantulas – The Gift for the Person Who Has Everything…",
	"MLS#2110… Nobody has died yet on these 11.90 acres. Small home, wood, pasture, stream. $144,900 740-965-….",
	"WANTED – Workaholic for special department, all shifts.  Highly reliable – no vacation or sick leave.  Must be flexible, intelligent and friendly.",
	"Christmas Sale. Handmade gifts for the hard-to- find person.",
	"WANTED: Medium sized dog house for low income family. Call 269-….",
	"PROVED! Make Bedwetting Easier… Waterproof Mattress Protector $19.95",
	"If you have over forty eyes and have noticed how your vision has changed…",
	"Bald, fat, short, and ugly male, 53, seeks short-sighted woman with tremendous sexual appetite.",
	"6 Foot TREE OF LIGHTS Reg. $49.99 – Save 20% LIGHTS NOT INCLUDED…",
	"FREE YOUNG GOAT for butchering or companion animal, call…",
	"And now, the Superstore – unequaled in size, unmatched in variety, unrivaled inconvenience.",
	"2 female Boston Terrier puppies, 7 wks old, perfect markings, 555-1234.  Leave mess.",
	"FOUND – dog dressed in a superman costume (304) 417-….",
	"Free puppies: ½ cocker spaniel, ½ sneaky neighbor’s dog.",
	"MOVING SALE – EVERYTHING IS FREE AND MUST GO IMMEDIATELY!!!  ITEMS ALREADY AT THE CURB FOR CONVENIENT LOADING!!!",
	"… featuring Kohler Lite Flush Toilets – Live Demonstration – See How They Perform…",
	"WANTED – Air Traffic Control. No Exp. Needed: we train, HS grads 17–34. Great pay, benefits. Must relocate. Call M-F…",
	"Channel 16 temporarily off the air due to technical improvements",
	"This ad may not be the best lonely heart in the world, nor its author the best-smelling. That's all I have to say. Man, 37.",
	"NEPTUNE FRONT LOAD WASHER – Built-in high definition tuner – Digital cable ready with cable card slot – Built-in 20 watt stereo speaker system – SALE $799",
	"JOB OPPORTUNITY IN BROADCASTING – PT Janitor/maintenance-general janitorial, clean, sanitize, dust, polish, spot wash, vacuum, empty trash, gather recyces, replace light bulbs. Send resume to: MARIA ADAMS, KTSH 100 Valley Dr., Brisbane, Ca 94005. Fax 415-467-…. EOE. DEADLINE 4/12/96.",
	"Mother’s Day Gift – FREE SALAMI – Steve’s Deli…",
	"PART-TIME HELP WANTED. Must have creative skills, drivers license and car with outgoing personality",
	"HELP WANTED – DoodyCalls Technician",
	"March 8th – Hypnotist Frank Santos – Donation $10 – All you can eat – Bring your own food – Starts at 8pm…",
	"His and hers bicycles, $25 each or both for $55.",
	"Now I know what to do the next time my patents die… – If you are inheriting someone’s IRA/401K/TSP or Annuity…",
	"Bet us your letter of business translation do. Every people in our staffing know English like the hand of their back. Up to the minuet wise-street phrases, don't you know, old boy.",
	"FOR SALE: 1993 Chevy Lumina. Black exterior with beige interior. Runs and drives great. Sorry, no tires included.",
	"WANTED – COMMERCIAL SPACE HUNTER",
	"Bald, fat, short, and ugly male, 53, seeks short-sighted woman with tremendous sexual appetite.",
	"Professional Texas Hold’em Polka Table, new, still in box. $250/best 508-916-….",
	"TALKING DOG, speaks 4 languages, only $50. 309-693-….",
	"JACK RUSSELL terrorist puppies. 2 boys, 2 girls, 5 weeks old. $400 each. 725-….",
	"Ambulance Service – Non-Emergency – Sims Funeral Home",
	"It Takes Many Ingredients to Make Burger King Great But…  “The Secret Ingredient is Our People”",
	"LOST African Elephant. Call 281-701-….",
	"HAMSTERS free.  Call Allen’s Mom …  –  HAMSTERS $1.00 each. Call Allen …",
	"I'm just a girl who can't say 'no' (or 'anaesthetist') [sic]. Lisping Rodgers and Hammerstein fan, female lecturer in politics (37) WLTM man to 40 for thome enthanted eveningth.",
	"HELP WANTED – Administraive/ Secretary",
	"FOUND – dog dressed in a superman costume (304) 417-….",
	"Ahigrim & Sons Lts. Funeral Parlor and Mini-Golf, 201 N. Northwest Hwy., Palatine, (847) 358-….",
	"Free internet access … $99.",
	"LAWN MOWER – Tends to catch on fire but put out easily with garden hose $30. Please call 258-….",
	"Looking for a small “13 inch” male registered Beagle to breed with our little girl. Call 862-….",
	"Ensure your next erection is in safe hands.",
	"CORRECTION – In a recipe for salsa published recently, on of the ingredients was misstated…  The correct ingredient is “2 tsp. of cilantro” instead of “2 tsp. of cement.”",
	"Boa Constrictor – Great With Kids! – 2 Years old, approximately 2 feet long. Includes tank with light and accessories. $150 Call…",
	"Car Sitting Services: Are you going away for a long trip? Are you afraid your car will be lonely, or worse yet, stolen!? I can protect your car and take it for long drives to keep it company. I can even drop you off and pick you up at the airport using your car (at my convenience)! Cheap rates! Call [telephone] and ask for One-tooth Tony.",
	"RABIES CLINIC & BAKE SALE 1–3 PM – $8.00/Animal – Keezletown Ruritan Hall…",
	"Want to Buy • City council candidate. Would like to rent or buy a bullet proof vest for 10 months. 384-….",
	"LOST: Camera with personal pictures from ladies restroom at Lorain County Fair. No questions. Please contact 926-….",
	"Dillards 60% off Christmas Sale! – From December 14–21 Dillards will be having the largest sale of the year on cloths, toys, fits, household items, furniture and jewelry, shoes, hats, mens wear and evening wear, just in time for Christmas! There will be a Special Appearance by Satan between the hours of 5pm until 9pm for your kids!… [sic]",
	"PET OF THE WEEK • Let this dog, Pea, in your home.",
	"HEY KIDS…  Santa will be at Viking Liquor Sunday Nov. 26, 11 am–3 pm FREE PICTURES • VIKING LIQUOR • KIDS! Bring your pet!",
	"PET DOOR; 8 ft. tall, never used, $80.00, 358-….",
	"Singer/lyricist looking for untalented musicians to form punk band. Call… & ask for Adam.",
	"Mild or Hot – OLD FOLKS Sausage 2/$5…",
	"Sick of your: Job-Boss-Paycheck-Life? My Business Is Growing To Fast!!!! [sic] $800-4000/mo. Part-Time work at home – work at the office – just work no age limit – no experience – just cash!!! CALL 504-6367 TODAY",
	"Attention male London Review of Books readers: 'Greetings, earthling – I have come to infest your puny body with legions of my spawn' is no way to begin a reply.  Female, 36 – suspicious of any men declaring themselves to be in possession of a 'great sense of humor.'",
	"STAFF NEEDED FOR GOURMET BURGER BAR THAT NEEDS STAFF",
	"Read Weight in the Palm of Your Hand! … No More Bending Over or Looking Down!",
	"Silk? Tweed? Hopsack? Worsted? No matter what your topcoat is made of, this miracle spray will make it really repellent.",
	"Free Yorkshire terrier.  8 years old. Hateful little dog. Bites.",
	"MUST SELL: 3 grave spaces in Laureland, very reasonable. Plus air conditioner.",
	"WANTED: Hair cutter. Excellent growth potential.",
	"MOVING SALE – EVERYTHING IS FREE AND MUST GO IMMEDIATELY!!!  ITEMS ALREADY AT THE CURB FOR CONVENIENT LOADING!!!",
	"Wanted: dead gentle pony! 941-637-….",
	"BEAUTIFUL ENGAGEMENT ring. Yellow gold, wide band with 18 diamonds set in 3 rows of 3 diamonds on each side of one large round-cut center stone. worn, sparingly, for only 9 Days. “It Didn’t Mean Anything. It was just suppose to Shut Her Up.” It didn’t shut her up. Happy to be Rid of it too. For the first offer of $800.00. Phone… between 9 a.m. – 9 p.m.",
	"CAB DRIVERS WANTED – Nights & weekends. Must have good driving & criminal record.  Apply in person, 151 Elm St.",
	"WANTED – COMMERCIAL SPACE HUNTER",
	"PREGNANT PYGMY goats. Two males, 2 and 3 years old. 237-….",
	"SITUATIONS WANTED – WILL CLEAN your home, will take in washing & ironing in my home. Will also tattoo pet dog at your home. 297-….",
	"GOLD Fish: Needs good home. Is irritable but enjoys TV, $2. Phone…",
	"Now you can borrow enough money to get out of debt.",
	"FREE Rent in exchange for elderly woman. 319-233-….",
	"Sinister-looking man with a face that only a mother would love: think of an ageing Portillo with a beard and you have my better-looking twin. Sweetie at heart, though. Nice conversation, great for dimly-lit romantic meals. Better in those Welsh villages where the electricity supply can't be guaranteed. Charitable women to 50 appreciated. Box…",
	"24 Hr. Day Care – All Ages – $65 Weekly For Day Shift – Torturing Available. Parents night out on weekends. 983-…",
	"FOR SALE – Diamonds $20; microscopes $15.",
	"If You Had No Idea What To Get Her For Valentine’s Day… Imagine How Overwhelming Arranging Her Funeral Would Be.  Give her the perfect gift, make pre-arrangements as a couple with the affordable funeral home. Choose from affordable funeral services or affordable cremations. Compassion is our passion…",
	"Free inside mini golf. Call ahead, because play is canceled if there is any funeral work. “We want folks to know we’re not so scary” we’re people. A funeral parlor is not a dark place, but a safe and secure one…",
	"FOR SALE: Instant coffee table",
	"We build bodies that last a lifetime.",
	"For Adoption: 2 female Chihuahua, both crate trained. Also 1 male Old English sheep dog, w/2 glass eyes. Good guard dog. Adoption fee $50 to $100. For more information call…",
	"HAVE VIAGRA. Need woman. Any women between 18 & 80. PO Box ###. Boise, ID 83701.",
	"FREE PUPPIES…  part German shepherd, part dog",
	"CIRCUS going out of business, small, elephant, free to good home. (973)…",
	"FOR SALE – Eight puppies from a German Shepperd and an Alaskan Hussy.",
	"Allan’s Aquarium & Pet Center  – After-Easter Tarantulas – The Gift for the Person Who Has Everything…",
	"WANTED – Air Traffic Control. No Exp. Needed: we train, HS grads 17–34. Great pay, benefits. Must relocate. Call M-F…",
	"Employed in publishing? Me too. Stay the hell away. Man on the inside seeks woman on the outside who likes milling around hospitals guessing the illnesses of out-patients. 30-35. Leeds.",
	"92’ BLK VOLKSWAGON CABRIOLET Answers to the name April. Last seen in Towson near the YMCA. Yes, Owner is Blonde. If found please call Button…",
	"Used Tombstone, perfect for someone named Homer HendelBergenHeinzel. One only.",
	"DOWNERS GRTOVE – Stonewall Ave. Sat 10/18 & Sun 10/19 9am – 5pm – Dead Peoples Old Stuff. Oak stenciled table, tools, medical aids, Whirlpool, wheelchair, casino items, beer signs, many collectibles.",
	"Creative daily specials, including select offerings of beef, foul, fresh vagetables, salads, quiche.",
	"ALZHEIMER'S CENTER PREPARES FOR AN AFFAIR TO REMEMBER.",
	"Mrs. Jody Defries is pleased to announce the arrival of Elijah Joel – 8 pounds 10 ounces… and the loss of twenty pounds.",
	"A BIG THANK YOU! To all the people that stopped to help the injured Ostrich on Hwy 2 Weest. We will be having an Ostrich tasting at THE RANCH on Sunday Aug 9, 1–5 PM. All are invited, children welcome, no pets please, 29 miles west on Hwy 2 854-….",
	"Mature gentleman, 62, aged well, noble grey looks, fit and active, sound mind and unfazed by the fickle demands of modern society seeks… damn it, I have to pee again.",
	"Restaurant Assistant Manager: Applicants with the necessary experience need not apply.",
	"Design House Furniture Galleries FATHER’S DAY CHAIR SALE 30 to 50 % off list price – Give Father His Own Electric Chair…",
	"HELP WANTED – Remedy Engineer",
	"Snake for sale. Five-foot boa constrictor – only $5 per foot.  Must buy entire length.",
	"Government employer looking for candidates.  Criminal background required.",
	"HEY KIDS…  Santa will be at Viking Liquor Sunday Nov. 26, 11 am–3 pm FREE PICTURES • VIKING LIQUOR • KIDS! Bring your pet!",
	"Easygoing athletic SJM, 41, seeking SF, looks not important, must be tall, slim and attractive.",
	"WE FEATURE Indoor Shooting Range – E-Z Layaway Program – Concealed Carry Classes – Full Line Security Leather – Machine Gun Rentals – Certified NRA Instructors…",
	"You’re all invited to Steak & Shrimp – Every Friday Night – 5:30 pm – 10 pm – Have Some Fun!! Bring A Gun!!  Cash Can Be Won!!  At Our Trap Range…",
	"Get rid of aunts. Zap does the job in 24 hours.",
	"Wanted: Lifeguard. Must be able to swim.",
	"WAITRESS NEEDED. Must be 18 years old with 20 years experience. Apply in person Carnation Restaurant.",
	"Liberty Gathering Place – Menacemeat Pie all Weekend – Open until 8:00pm Friday Night, 465-…. [sic]",
	"MEDICAL Assistant, Full Time, Wanted For Growing Medical Practice, Competitive Salary. No Health Benefits. Send Resume to…",
	"Square coffee table 53” Long X 21” Wide with storage, $80. 453-….",
	"Dog for sale: eats anything and is fond of children.",
	"Harrisburg Postal Employees Gun Club",
	"Sheer stockings.  Designed for fancy dress, but so serviceable that lots of women wear nothing else.",
	"Bastard. Complete and utter. Whatever you do, don't reply – you'll only regret it.",
	"MECHANIC – Now hiring full time mechanic. Must be mechanically inclined. Brenny’s Cycle Works …",
	"Allan’s Aquarium & Pet Center  – After-Easter Tarantulas – The Gift for the Person Who Has Everything…",
	"Seekers of Silence – Contemplative Saturday morning, “Rediscovering the Value and Joy of Fasting,” 8:30–noon. Feb. 14th, John XXIII University Parish… Bring lunch",
	"Philanthropy is my middle name. It's just a name though so don't be expecting any free rides. You can call me Mr Wallace. My first name is none of your business. Applications to box no. 9741.",
	"PREGNANT PYGMY goats. Two males, 2 and 3 years old. 237-….",
	"The Brandywine Gourmet – Stop in to enter drawing to guess height & weight of our GIANT 3 ft., 20 lb. Chocolate Bunny!…",
	"FOR SALE. Three canaries of undermined sex.",
	"Will the person who got hit in the head with a tomato in the 1950’s please contact (414) 453…",
	"Notice: To person or persons who took the large pumpkin on highway 87 near Southridge Storage. Please return the pumpkin and be checked. Pumpkin may be radioactive. All other plants in vicinity are dead.",
	"Get a little john: the traveling urinal holds 2 1/2 bottles of beer.",
	"Semi-Annual after-Christmas Sale.",
	"No matter what your topcoat is made of, this miracle spray will make it really repellent.",
	"Dog for sale: eats anything and is fond of children.",
	"You're a brunette, 6', long legs, 25-30, intelligent, articulate and drop-dead gorgeous. I, on the other hand, am 4'10\", have the looks of Herve Villechaize and carry an odor of wheat. No returns and no refunds at box…",
	"WANTED: Used Paint",
	"Are you Kate Bush?’ Write to obsessive man (36). Note, people who aren't Kate Bush need not respond.",
	"FOR SALE • OLDER CLOTHES DRYER. Works well but needs new home. Will trade for 2 large packages Oreo double stuffed cookies (unopened). Phone…",
	"Wanted: Tudor [sic] needed for help in English class.",
	"Corduroy Pillows: They're making headlines!",
	"Ensure your next erection is in safe hands.",
	"FREE TO GOOD HOME – Beautiful 6 mo. old male kitten — orange & caramel tabby, playful, friendly very affectionate, ideal for family w/ kids. OR Handsome 32 yr. old husband – personable, funny, good job, but doesn't like cats. Says he goes or cat goes. Call Jennifer  265-…. — come see both and decide which you'd like.",
	"WANTED: Hair cutter. Excellent growth potential.",
	"Ahigrim & Sons Lts. Funeral Parlor and Mini-Golf, 201 N. Northwest Hwy., Palatine, (847) 358-….",
	"Wanted: Limo driver needed for overnight transport of drunk and drugged up clients.",
	"I've divorced better men than you. And worn more expensive shoes than these. So don't think placing this ad is the biggest comedown I've ever had to make. Sensitive F, 34.",
	"*1990 SUBARU Justy. 5-speed, fuel injection, new brake and drum. New exhaust system, 4 new street tires and 2 studded. Body in great shape. Engine gone, but still runs. $500. 247-….",
	"GOLD Fish: Needs good home. Is irritable but enjoys TV, $2. Phone…",
	"Manure Digester Summit, 9:30am–3pm, $20 includes lunch…",
	"hairorobert – IF WE CAN’T MAKE YOU LOOK GOOD…  YOU UGLY! – 757-….",
	"Girl wanted to assist magician in cutting-off-head illusion. Blue Cross and salary.",
	"Georgia peaches, California grown – 89 cents lb.",
	"Home Made Portable Toilet. Great for parades $90/ 764-….",
	"Mother’s helper – peasant working conditions.",
	"Sheer stockings.  Designed for fancy dress, but so serviceable that lots of women wear nothing else.",
	"10 FREE French Fry Certificates for only $1.00",
	"Sterling Optical – FREE eye with Purchase of a Prescription Pair of Eyeglasses",
	"Give Dad What He Always Wanted! A Weekend For Both of You in The Nude. • We Set The Mood. You Provide The romance. • They are back… Paradise Valley Resort – Georgia’s Premier Clothing Optional Resort – 3 pools • 2 hot tubs • NO CLOTHING! – Day Visitors Welcome …",
	"My other car is a bike. Eco-friendly bio-diverse M (29). Smells a bit like soil and eats too much soup, but otherwise friendly (you're not seriously going to put that burger in your mouth, are you?).",
	"Enthusiastic and alive with a desire to lead others",
	"Only quiet living people need apply.",
	"Beat the Christmas Holiday Rush – Order Now – Choosing your Monument now, means your loved ones won’t be faced with the hardship during their time of grief.  STEEDLEY MONUMENT WORKS",
	"WANTED: chambermaid in rectory. Love in, $200 a month. References required.",
	"Have several very old dresses from grandmother in beautiful condition.",
	"Star Wars Job of the Hut – $15",
	"Are you Kate Bush?’ Write to obsessive man (36). Note, people who aren't Kate Bush need not respond.",
	"Mt. Kilimanjaro, the breathtaking backdrop for the Serena Lodge. Swim in the lovely pool while you drink it all in.",
	"WANTED – COMMERCIAL SPACE HUNTER",
	"WANTED: Widower with school age children requires person to assume general housekeeping duties.  Must be capable of contributing to growth of family.",
	"German shepherd. 85 lbs. neutered. speaks German. free.",
	"Lost: Search & Rescue Dog – From 13th and Peoria area. Sunday, May…",
	"Give Blood & Make Your Own Sundae, July 13th",
	"Wanted, man to take care of cows that does not smoke or drink.",
	"Sterling Optical – FREE eye with Purchase of a Prescription Pair of Eyeglasses",
	"Cure Sleepiness Right Away – Time for Use: Long-Distance Driving, Drunk Driving, Night Driving…",
	"Remember, you get what you pay for. And at Hub Furniture Store, you pay less.",
	"Nordic track $300 – hardly used – call Chubby.",
	"Corduroy Pillows: They're making headlines!",
	"To all you hunters who kill animals for food, shame on you; you ought to go to the store and buy the meat that was made there, where no animals were harmed.",
	"Call 800-826-8086 (Central Time) – RTPatch® Professional",
	"Professional Texas Hold’em Polka Table, new, still in box. $250/best 508-916-….",
	"2-FUDGE PACKING MACHINES, $300. Ea. … Steve or George",
	"WANTED: Preparer of food. Must be dependable, like the food business, and be willing to get hands dirty.",
	"FOR SALE – Easy chair, Kitchen table, Chester Drawers. 982-….",
	"WANTED – Air Traffic Control. No Exp. Needed: we train, HS grads 17–34. Great pay, benefits. Must relocate. Call M-F…",
	"Sean – You are such a disappointment to the entire family – don’t bother coming home. Love, Dad",
	"Mercury Fish & Chips",
	"Super Bowel Party – Sunday January 30th – Complimentary Buffet…",
	"SNOW BLOWER for sale… only used on snowy days.",
	"CHRISTIAN woman looking for Christian man partner who is sympathetic with woman who has mental illness and hears voices but is self controlled. Phone…",
	"ARTIFICIAL CHRISTMAS TREE – For Sale. Like new. Needs stand, ornaments, lights, and branches. $99.00 firm. Call…",
	"ADVERTISING COMPANY NEED one male talent, shooting the back only with our product kitchen stuff, please send your picture. If you are interested…",
	"WE FEATURE Indoor Shooting Range – E-Z Layaway Program – Concealed Carry Classes – Full Line Security Leather – Machine Gun Rentals – Certified NRA Instructors…",
	"Spakling Wines – with Iron Horse Vineyards – a blend of 30% Chardonnay…",
	"It’s Summertime! – Bring Your Children to the: Garma Specialty Clinic for Circumcision – Adult and Children – Painless, Bloodless…",
	"Three black convicts, healthy and well behaved, need good home, pkg deal. 608-427-….",
	"POMERANIAN POPPIES per bread, 7 wk. on 4-16-08 decals removed, teddy bear faces, very cute, $300 884-….",
	"Caffe Allegro – In downtown Middletown –Discover why so many Italians would prefer to eat at home",
	"Attention male London Review of Books readers: 'Greetings, earthling – I have come to infest your puny body with legions of my spawn' is no way to begin a reply.  Female, 36 – suspicious of any men declaring themselves to be in possession of a 'great sense of humor.'",
	"FREE DUCKS. You catch.",
	"Help wanted: Boiler operator. Previous clinical experience with gynecology patients required.",
	"John Deere self propelled 22” lawn mower. “As new”. Bought for wife. Bad idea. Top of the line. Elec. Start, bagger etc. Paid nearly $600.00. Will sell for $400.00 for best…",
	"FOR SALE. Three canaries of undermined sex.",
	"Bald, fat, short, and ugly male, 53, seeks short-sighted woman with tremendous sexual appetite.",
	"Branford: 895,000 Steps to beach. Set on nearly an acre is this historic colonial w/modern amenities. Call for the special features…",
	"FOR SALE:  One pair hardly used dentures, only 2 teeth missing.  $100 OBO.  Call Ira…",
	"Nemesis Wanted: I’m 5’10”, into kayaking, books and conversation (by day), justice, honour and vengeance (by night). Seeking arch-enemy, possibly crimelord or deformed megalomaniac. Call…",
	"NEW LISTING – CARBONDALE – Move right into this 3 bedroom, 1.25 bath home, featuring foyer with split staircase, mysterious hidden commode, off street parking yard. $79,900.",
	"Buy Any New Vehicle & Receive A Gas BBQ! – (Cost of promotion may increase price of vehicle) …",
	"Remote Controlled Genitalia – Think of all the fun you’ll have!!! …",
	"Advanced Products, Inc. • 605 East Robins, Conway, Arkansas 72032 • 10% Satisfaction Guaranteed • DIRECTIONS – Take 1 to 3 tablets daily after breakfast as a dietary supplement.",
	"MLS#2110… Nobody has died yet on these 11.90 acres. Small home, wood, pasture, stream. $144,900 740-965-….",
	"Mom & Daughter PJ Night Friday: October 8 6:30–9:30 pm – Summitt – Bring your favorite Mexican",
	"LOST: Camera with personal pictures from ladies restroom at Lorain County Fair. No questions. Please contact 926-….",
	"FOR SALE: Lee Majors (6 Million Dollar Man) – $50",
	"TURKEY – FOR SALE. Partially eaten. Only eight days old.  Both drumsticks still intact. $23.00 OBO",
	"We'll move you worldwide throughout the country.",
	"$17,962 – ’98 Lincolon Town Car",
	"OUR SOFA seats the whole mob and it's made of 100% Italian leather.",
	"QUESTION OF THE DAY – Question: What constitutes a millionaire?  •  Answer: A millionaire is someone who has $1 million, according to Jerry Beto, branch manager and senior vice president of investments at AG Edwards and Sons.",
	"Lost: small apricot poodle.  Reward.  Neutered.  Like one of the family.",
	"WE FILL ALL PRESCRIPTIONS We Fill All Compounded (Mixed) Prescriptions According To Your Doctor’s Instructions. If Your Doctor Writes You A Prescription For A Specially Prepared Suppository, We Can And Will Fit It….",
	"CARL’S OXFORD DINER – Mention This Ad for a Free Ice Water – 291 Main St. Oxford",
	"HAMSTERS free.  Call Allen’s Mom …  –  HAMSTERS $1.00 each. Call Allen …",
	"Your buying me dinner doesn't mean I'll have sex with you. I probably will have sex with you, though. Honesty not an issue with opportunistic male, 38.",
	"To all you hunters who kill animals for food, shame on you; you ought to go to the store and buy the meat that was made there, where no animals were harmed.",
	"Thurs. – Skateboard Expo will be from 4 pm to 5:30 pm E. Center Street. Free. Sponsored by the Rochester Area Brain Injury Community Committee.",
	"Allan’s Aquarium & Pet Center  – After-Easter Tarantulas – The Gift for the Person Who Has Everything…",
	"Maternity sweater, $52. Comes in unisex sizes.",
	"HELP WANTED – Remedy Engineer",
	"PRO PAIN TANK – Camping Size. $20 (408)266-…."
]